### ISSUE TITLE
Warning message when deleting a variable with derivations

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/rcrunch#102]
Background: I have a "tracker" survey that gets a new wave of data every 2 months. In this survey are some derived variables. I had to delete one of the variables that has other variables derived from it. I forgot about the derived variables and so they were out of sync. 

Feature request: when you delete a variable in rcrunch that has other variables derived off of it, a warning message to appear that say "Warning: the variable you want to delete has variables derived off of it: _name_derived_var(s)_,  are you certain you want to proceed?"

Thank you.

**Comment by gergness** [comment]
Won't fix
