### ISSUE TITLE
changeCategoryID causing mismatched category $values

### ISSUE THREAD

**Issue by zach-zussman** [Crunch-io/rcrunch#103]
The more recently implemented version of changeCategoryID has this line which was not present in the originally used function:
newcat$numeric_value <- to
but it doesn't seem to check if the variable is 'missing' or not.   This makes it so using changeCategoryID on for example a streaming dataset to change categories to match an uploaded dataset, you end up with mismatched category values.  The uploaded dataset by default has NA for values for missing categories and the streamed-and-changed dataset will have the id #'s as values for any missing categories.

**Comment by jonkeane** [comment]
We've just merged some code that updates this behavior. Now, the numeric value of a category will not be changed unless the id and the numeric value are the same before calling `changeCategoryID()`.
