### ISSUE TITLE
as.data.frame ids

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#106]
as.data.frame has been working really well! It would be amazing if it had the categorical='id' option that exportDataset has! Then I would remove exportDataset (and write.csv) from my scrips

**Comment by persephonet** [comment]
Additionally, as.data.frame doesn't currently seem to allow hidden variables.

**Comment by persephonet** [comment]
Another note: as.data.frame does not return the variables in the order you asked for them

**Comment by jonkeane** [comment]
Most of these should be addable pretty easily. For the ordering of variables, were you wanting a syntax like `as.data.frame(ds[c("var5", "var2", "var1")])` to produce a CrunchDataFrame with the columns var5, var2, var1 in that order?
