### ISSUE TITLE
conditionalTransform append

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#107]
conditionalTransform does not update with new (appended) data. I'm not sure if that's expected behavior, but it would be really helpful if it did update

**Comment by nealrichardson** [comment]
That is expected. There is no server-side derivation function for conditional transformations yet. Whenever that is implemented, the result of `conditionalTransform` will be derived and will update with new data. But there's nothing to be done on the R side until that function exists on the server.
