### ISSUE TITLE
Implement cube "transforms"

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/rcrunch#121]
These are settings that affect how cube query results should be displayed: things like suppressing certain elements, reordering, renaming, and inserting "headings" and "subtotals" (AKA "nets"). This last feature is the motivating force behind the feature request. 

See http://docs.crunch.io/#transforming-analyses-for-presentation. @malecki can answer any questions about the features. We probably even have some google docs with specs. 

We will drive out the implementation of this feature in the API, web app, and excel exports by starting in R. First step: design the R interface to setting the "transforms" on variable entities, viewing the transform that exists, and editing them. Implementing this will facilitate the frontend/exporter development because it will make it easy for us to create the test fixtures (variables, cube queries) that can be used everywhere. Next: apply them appropriately in the `CrunchCube` methods.

**Comment by jonkeane** [comment]
The first iteration of this was merged with #139
