### ISSUE TITLE
Reorder vignettes in Git

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/rcrunch#122]
Small one, reorder the vignettes so that "Getting Started" is at the top of the list, maybe rename it to "1. Getting Started". This way a newbie will be more likely to start off on the right foot.

**Comment by GitBrianLaw** [comment]
On git hub itself:
https://github.com/Crunch-io/rcrunch/tree/master/vignettes

and when I do “?? Crunch” inside R

And when I navigate through the help pages in R to the page “vignettes and other documention”.

It’s alphabetical in all of these so that “analyze” is first.

As long as getting started comes first we should be good b/c there’s the “take the next one here” link that progresses people through.

**Comment by GShotwell** [comment]
I'm not opposed to reordering the file names, but it's probably good to start directing people to the package website http://crunch.io/r/crunch/ instead of the github page for documentation. We should also add a link to the website from the github README

**Comment by nealrichardson** [comment]
I think this is resolved now.
