### ISSUE TITLE
is.selected vectorized

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#123]
is.selected is a property of each Category in a multiple_response variable. It would be great if it was a property of Categories of a multiple_response variable so instead of `names(categories(ds$mr_var))[sapply(categories(ds$mr_var), is.selected)]` I could do `names(is.selected(categories(ds$mr_var)))` like I can with `names(is.na(categories(ds$mr_var)))`

**Comment by nealrichardson** [comment]
In the code: https://github.com/Crunch-io/rcrunch/blob/master/R/categories.R#L188 exists for `is.na.Categories`, and while there is https://github.com/Crunch-io/rcrunch/blob/master/R/category.R#L121 for `is.selected.Category` there is no similar one for `.Categories`

For completeness, we'd probably also want the `is.selected.Categories<-` methods too.
