### ISSUE TITLE
crtabs unweighted base

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#124]
Currently, to get the unweighted base of a crtabs, I have to do acrobatics based the number of variables and types of variables. Given that information is already within with the CrunchCube, it would be great if it were formatted in a friendlier way to avoid such convoluted code.

**Comment by nealrichardson** [comment]
I'm not sure what acrobatics and convolutions you're going through, but is `bases()` lacking in some way? That's the method that accesses the unweighted counts in a CrunchCube. See http://crunch.io/r/crunch/reference/cube-computing.html#details.

**Comment by persephonet** [comment]
Thank you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Persephone Tsebelis
Senior R Programmer

[YouGov  What the world thinks]
650 5th Street, suite 505
San Francisco, CA 94107
Persephone.Tsebelis@yougov.com<mailto:Persephone.Tsebelis@yougov.com>



---------------------------------------------------

________________________________

**Comment by persephonet** [comment]
(Currently testing it on every variable type.) Just FYI:


cr <- crtabs(mean(waveno) ~ 1, ds, weight=ds$weight)​

[crunch] > bases(cr)
Error in dimnames(data) <- dimnames(x) : 'dimnames' applied to non-array

waveno is numeric.




Persephone Tsebelis
Senior R Programmer

[YouGov  What the world thinks]
650 5th Street, suite 505
San Francisco, CA 94107
Persephone.Tsebelis@yougov.com<mailto:Persephone.Tsebelis@yougov.com>



---------------------------------------------------

________________________________

**Comment by nealrichardson** [comment]
Fixed.

**Comment by persephonet** [comment]
Normally if you go out of the allowed margins it errors but now with numerics 
```
cr <- crtabs(mean(waveno) ~ 1, ds)
[crunch] > bases(cr)
[1] 216446
[crunch] > bases(cr, margin=1)
[1] 216446
[crunch] > bases(cr, margin=2)
[1] 216446
[crunch] > bases(cr, margin=3)
[1] 216446
[crunch] > bases(cr, margin=4)
[1] 216446
[crunch] > bases(cr, margin=5)
[1] 216446
```
