### ISSUE TITLE
More methods for accessing variable metadata in CrunchCubes

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#131]
Can types and notes please be added as CrunchCube methods?

**Comment by nealrichardson** [comment]
Also expose variable metadata for "measures" variables (from support email)

**Comment by nealrichardson** [comment]
Started a branch for this, which you can feel free to check out and play with. Some observations/caveats/items for discussion:

* You can access a pseudo-VariableCatalog of information about the variables in the dimensions with `variables(cube)`. `notes(cube)` just calls `notes(variables(cube))`.
* The metadata you get here describes the cube dimensions, not the input variables exactly. There are some differences. Categorical arrays, for example, are one variable in your input but return two dimensions. And you may see an "enum" in `types(cube)`. 
* Metadata on the "measures" variables--the left-hand side of the formula, means and medians etc.--is present in the cube object, and we can expose that similarly, but there are some design questions. Should `variables(cube)` contain all variables from `dimensions` and `measures`? Probably so, but then the order of results in `variables(cube)` (and thus `aliases(cube)` et al.) wouldn't be meaningful/map to the order of the dimensions. Maybe that's fine, and if you want order, access the metadata like `aliases(dimensions(cube))` or `aliases(measures(cube))`.

**Comment by nealrichardson** [comment]
https://github.com/Crunch-io/rcrunch/pull/141 did more, including adding a `measures` method and exposing that metadata, though there are some gaps in what the server returns. Closing this for now as resolved, but we can open a new issue if there are specific needs or bugs.
