### ISSUE TITLE
Remove limitation on large as.data.frame requests

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/rcrunch#150]
We currently have a [restriction](https://github.com/Crunch-io/rcrunch/blob/master/R/as-data-frame.R#L51-L56) that prevents users from pulling down an entire dataset's worth of columns. The intent was to avoid accidentally triggering a long, slow download process and to encourage finding ways to perform actions without pulling down all of the data. In practice, users will download the data by other means (csv export) instead of using the `as.data.frame` methods. 

Instead of aborting the request in as.data.frame, switch behavior and load a data.frame by calling write.csv and reading that back in. Save our users the step they're already doing, and in the process preserve the Crunch metadata better. Some considerations:

* The csv method should respect the [categorical mode](https://github.com/Crunch-io/rcrunch/blob/master/R/as-data-frame.R#L22) setting and equivalently convert categorical ids to factors if desired. To do that efficiently, use the [variableMetadata](https://github.com/Crunch-io/rcrunch/blob/master/R/variable-metadata.R#L11) function to get all of the category metadata for the dataset in a single GET.
* Make sure you can test both code paths for the same dataset so that you can assert that the result of doing `as.data.frame` is the same either way. The ["crunch.data.frame.limit" option](https://github.com/Crunch-io/rcrunch/blob/master/R/as-data-frame.R#L51) was one way to make the function more testable, but maybe it's not the best one. A different pattern in `crunchBox()` is a [function that can be mocked](https://github.com/Crunch-io/rcrunch/blob/master/R/crunchbox.R#L137-L138) in tests when you want to change the behavior.
* The current 10k cells threshold for switching behavior is somewhat arbitrary. When you have the ability to switch between the `as.vector`-every-column mode and the `read.csv(write.csv())` mode, you can do some benchmarking with different datasets and selections of numbers of variables and rows and see where the cutoff should be. A better criteria might be considering numbers of columns and rows separately. Exporting a csv will take a minimum of 5 requests (GET dataset's "export" view, POST to the csv endpoint, GET the progress resource location it returns, will have to GET that at least one more time before it's done, and then finally GET (download) the file), so if fewer than 5 variables are requested, the as.vector method may be faster. All that said, optimizing this threshold shouldn't be majorly blocking for getting the feature out. We can optimize later.
* If a `CrunchDataFrame` can have additional non-Crunch columns added to it, those should also appear in the `as.data.frame`'d version of it, regardless of how we fetch the rest of the Crunch data. 

While we should have a better solution for pulling lots of data without dumping to CSV as an intermediary (https://github.com/Crunch-io/rcrunch/issues/120), that requires significant backend work and lots of testing of the new format. CSV exists today, so let's use it today.

**Comment by GShotwell** [comment]
I did a bit of benchmarking of the two approaches on a large dataset with 50k rows and 150 column and a small dataset with 25 rows and 13 columns, and it looks like the csv download is faster for most cases. Times are user in seconds. 

Small dataset

| columns| csv_download| as.vector_download|
|------:|------------:|------------------:|
|      1|        0.039|              0.011|
|      2|        0.035|              0.024|
|      3|        0.049|              0.038|
|      4|        0.045|              0.046|
|      5|        0.045|              0.054|
|      6|        0.044|              0.061|
|      7|        0.046|              0.081|
|      8|        0.046|              0.075|
|      9|        0.050|              0.081|
|     10|        0.045|              0.083|

Large dataset

| colunms| csv_download| as.vector_download|
|------:|------------:|------------------:|
|      1|        2.353|              0.085|
|      2|        0.331|              0.221|
|      3|        0.439|              0.329|
|      4|        0.602|              0.593|
|      5|        0.617|              0.619|
|     10|        1.389|              1.507|
|     20|        2.937|              3.154|

So it looks like Neal's intutition was correct that right around 4 columns the csv download starts doing better than the as.vector download. That said, the difference is pretty small. Does it make sense to remove the as.vector download entirely just to simplify the code a bit. We lose a bit of speed for users downloading a small number of columns, but that seems like a less common problem than downloading more than 4 columns.

**Comment by nealrichardson** [comment]
`as.vector` itself should still exist for variables, but I'd be fine with always having `as.data.frame` do the CSV method.

Are your benchmarks against production or a local vm?

**Comment by GShotwell** [comment]
They're against production

**Comment by nealrichardson** [comment]
Fixed.
