### ISSUE TITLE
Transform : doesn't work

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#155]
I know it's still in dev but I thought I'd bring your attention to a little problem I had. 

`transforms(ds$baaQ2) <- Transforms(insertions = list(
    list(anchor = 2, name = "TOTAL AGREE",
        `function` = 'subtotal',
        args = list(1, 2)),
    list(anchor = 5, name = "TOTAL DISAGREE",
        `function` = 'subtotal',
        args = list(4:5))))`
does `Error: Server error: (500) Internal Server Error: An error occurred processing your request. We have been notified`

While changing the last line to `args = list(4, 5))))` works. Obviously it's because the list is of length 1 in the first example and 2 in the second. But maybe args could take a vector?

**Comment by nealrichardson** [comment]
Sounds like `Transforms` needs a `jsonprep` method that wraps `args` in `I()` so that they're always JSON-serialized as an array. Or something along those lines that achieves that effect.

**Comment by jonkeane** [comment]
I added some input validation which should prevent this from failing silently, but the crux of it was that `list(4:5)` is actually a list of length one with a vector of length two as it's first and only element, as opposed to `list(4, 5)` which is a list of length two.

```
> identical(list(4:5), list(4, 5))
[1] FALSE
```

Input checking on `Subtotal` will convert `list(4:5)` to `list(4, 5)`,  and there is input checking to ensure that `Insertion`'s `arg`s have the right shape without resorting to a server error. If you run into something similar or other pain points with `Subtotals` and `Heading`s please let us know!
