### ISSUE TITLE
"Nets" next steps

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/rcrunch#164]
Some issues/suggestions to address before we "release" the feature:

- [x] Apply transforms to any dimension
- [x] Transforms for cat arrays
- [x] transforms<- method for cube objects
- [x] Default anchor for Subtotal: if not specified, put it right after the last category being grouped
- [x] More documentation explaining Transforms, Insertions, Subtotals, Headings, how they relate, how they're different

**Comment by jonkeane** [comment]
- [ ] fix `show` method for heterogeneous `Insertions` class

**Comment by jonkeane** [comment]
Cat array transforms should work as soon as we can calculate insertions/transforms for columns. The first place to start with that would be to add a transform calculation for columns after [the row transforms are calculated ](https://github.com/Crunch-io/rcrunch/blob/master/R/cube-transforms.R#L98). 

Likely there will need to be some adjustment to figuring out which of the two dimensions each cat array variable provides to calculate the transform for.

For dimensions higher than 2, we might want to defer calculating subtotals for (although it is in principle possible), and instead concentrate on making `[` slicing methods for crunchcubes such that a user could slice the cube down to two dimensions and get the subtotals from that.
