### ISSUE TITLE
Get details about a user's interaction with a dataset

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#167]
A specific need was: the last time a user accessed a dataset. This can be accomplished with the code below (but should be expanded, validated, etc.:
```
last_accessed <- function (email, dataset_id) {
    users <- getAccountUserCatalog()
    user_url <- urls(users[email])
    ds_url <- shojiURL(UserEntity(crGET(user_url)), "catalogs", "datasets")
    
    httpcache::dropCache(ds_url)
    cat_df <- catalogToDataFrame(ShojiCatalog(crGET(ds_url)))
    one_ds <- cat_df[cat_df$id == dataset_id,]
    
    return(one_ds$access_time)
}
```

**Comment by nealrichardson** [comment]
That only will work if `email` corresponds to a member of the current user's account, which is probably not the use case that was envisioned. 

Instead, dataset editors can access a "users" catalog on the dataset, which has access time on it. Use that.

**Comment by nealrichardson** [comment]
See http://docs.crunch.io/#catalogs
