### ISSUE TITLE
feature request: an R fxn gui()

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/rcrunch#178]
Hello, 

Just a little convenience function called gui() that would return the url of the dataset you give it already in a format where when you copy paste it to a browser the dataset loads. Basically just self(ds) but swapping out the api/ and s in datasets and adding in /browse.

Not pressing, just a nice to have. Thanks.

**Comment by GShotwell** [comment]
Does the `webapp()` function do what you want? If not is there something we can add to that function?

http://crunch.io/r/crunch/reference/webApp.html

**Comment by GitBrianLaw** [comment]
Wow! webApp() is even better than what I had in mind. Thanks!

**Comment by GShotwell** [comment]
I'm going to close this for now, but we may want to change the name of `webapp` to something more verby like `openDataset` or `viewInCrunch`.
