### ISSUE TITLE
Compute z-scores against specific columns

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#203]
Users would like to calculate z-scores against specific columns/rows (as well as the pairwise comparisons of all columns/rows) rather than just compare to the marginals. 

Comparison to marginal is accomplished with [`rstandard()`](https://github.com/Crunch-io/rcrunch/blob/eeed75637efba6fc0f6a1078c197e3b3b6f304c8/R/cube-residuals.R#L51-L73) on a CrunchCube object. 

## Proposed interface
1. We need to add a `control` argument to `rstandard()` to select a column/row to test against (and a `dim` argument to specify if that's a column or row). If not specified `rstandard()` uses the same calculations as now (i.e. testing against the margins) See the `compare_to()` function in [Z-tests.pdf](https://github.com/Crunch-io/rcrunch/files/1732767/Z-tests.pdf)
2. We need a new function `pairwise_rstandard(cube, dim)` that should be able to be a wrapper around iterating through all of the columns/rows using `rstandard(cube, control, dim)` once (1) is implemented.

**Comment by jonkeane** [comment]
- [ ] change the name of `rstandard` to `z.scores` or `z.table` (we will alias back to `rstrandard` for backwards compatibility, but the mental model for `rstandard` is different enough from chi-square / z-score calculations to warrant some naming separation.
- [ ] although the current code for calculating z-scores works with a table limited to two columns or rows, we should provide a friendly interface: `[some friendly code here]`
- [ ] we should, initially limit the dimension that is being subset for comparison (that is, if I want to compare one column to another, the columns dimension) to only be categoricals and add MRs later

**Comment by malecki** [comment]
the crunchtabs consumer wants the `compare_columns_pairwise` matrix of Z scores.
