### ISSUE TITLE
Ensure that setEntitySlot doesn't accidentally overwrite parts of a slot

### ISSUE THREAD

**Issue by GShotwell** [Crunch-io/rcrunch#225]
We use setEntitySlot to change parts of entities, we want to make sure that when we do this we aren't accidentally overwriting parts of the slot which we aren't setting. For instance this code sets the `view` slow with a list which includes a `rollup_resolution` key. This is fine currently because `DatetimeVariables` only have the one view possibility, but if we later added another property, this code could overwrite that. We need to investigate and test `setEntitySlot` to ensure that it only changes the parts of the value list which are specified, and doesn't alter the parts which are ommitted. 

```
setMethod("rollupResolution<-",  "DatetimeVariable", function(x, value) {
        validateResolution(force(value))
        setEntitySlot(entity(x), "view", list(rollup_resolution = value))
        return(refresh(x))
})
```

**Comment by nealrichardson** [comment]
I believe our API does the right thing on PATCH. We should just confirm, whether with an integration test or some RTFS on the server side.
