### ISSUE TITLE
add `resolution<-` method to change the underlying storage resolution of a Datetime variable

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#234]
Hack around code: `crPATCH(self(variable), body=toJSON(list(resolution="WHATEVER")))`

**Comment by malecki** [comment]
should be easy peasy. the payload is 
```
crPATCH(self(variable), body=toJSON(list(resolution="WHATEVER")))
```

**Comment by nealrichardson** [comment]
And we already have a function to validate datetime resolutions.

**Comment by jonkeane** [comment]
Additionally: another idea, might be interesting to sniff the append error message and suggest functions. like, follow up `Different resolutions for datetime variable` with “See ?resolution”
