### ISSUE TITLE
More documentation / vignettes on our fork, edit, merge workflow

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#235]
Some package users have reported that the proper workflow for forking a dataset, editing it, and then merging the fork back to the original needs more expansion and reassurance that it is the right way to approach making major edits to a client-facing dataset.

Expand/edit documentation for:
- [x] `forkDataset()`
- [x] `mergeFork()`
- [x] `appendDataset()` (possibly referencing the fork/merge process)
- [x] `merge.CrunchDataset()` (possibly referencing the fork/merge process)

- [x] a vignette that shows the process from beginning to end.

**Comment by nealrichardson** [comment]
Done in https://github.com/Crunch-io/rcrunch/pull/259
