### ISSUE TITLE
deleteVariables should de-dup

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#268]
Currently, if you have the same variable in a list to delete multiple times, it will ask if you want to delete them (regardless of the number of times they are duplicated) and then error. It should dedup it for you so this does not happen:

```[crunch] > ds <- deleteVariables(ds, paste0("Q2_", kids_als$age_name))
Really delete these 21 variables? (y/n) 

[crunch] > ds <- deleteVariables(ds, paste0("Q2_", unique(kids_als$age_name)))
Really delete these 7 variables? (y/n) 

[crunch] > ds <- deleteVariables(ds, paste0("Q2_", kids_als$age_name))
Really delete these 21 variables? (y/n) y
Error: Client error: (404) Not Found: Variable 648effc1925249058d228945bcfa53b6 not found

**Comment by nealrichardson** [comment]
Looks like it just needs a `unique()` added to https://github.com/Crunch-io/rcrunch/blob/master/R/variable-delete.R#L27. Seems straightforward. Delete should be idempotent; you should not fail if you try to delete something that already doesn't exist.
