### ISSUE TITLE
copyOrder did not work on client dataset but does in a toy dataset

### ISSUE THREAD

**Issue by GitBrianLaw** [Crunch-io/rcrunch#274]
This is a weird one that may just be a mystery since I cannot replicate the problem with a toy dataset.

Using this script, you can see how copyOrder still does work correctly.
library(crunch)
login()

df <- data.frame('a'=1:10, 'b'=factor(letters[1:10]), 'c'=factor(LETTERS[1:10]))
ds <- newDataset(df, name="Testing copyOrder")
ds2 <- newDataset(df, name="Testing copyOrder ds2")

ds <- mv(ds, c('b', 'c'), "Group 1")
ds <- refresh(ds)
ordering(ds)
ordering(ds2)
ordering(ds2) <- copyOrder(ds, ds2)
ordering(ds2)

However, when I tried copyOrder earlier today on a long running tracker it did not. Here were the ids of the 2 datasets and an alias of a variable that you can see was in a group in one dataset but was not grouped after copying over the order.
[crunch] R > id(tracker)
[1] "8b347db95d6b4ebb85edea6395160205"
[crunch] R > id(tracker_old)
[1] "942ffa781d4f49278d297f863bed1958"
[crunch] R > # share with Craig and have him QC it.
[crunch] R > ordering(tracker) <- copyOrder(tracker_old, tracker)
alias `SQ16b_month_54_1`

Thank you.

**Comment by nealrichardson** [comment]
Will be reimplementing all this in https://github.com/Crunch-io/rcrunch/issues/323, so closing this one.
