### ISSUE TITLE
%in% doesn't always work in as.data.frame

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#289]
I might just be doing something wrong, but I'd expect `ds$keep %in% "True"` to return the same thing as `ds$keep == "True"` (given there are no NAs in keep)

[crunch] > ds$keep
keep (categorical)
Count
True   3069
False     0
[crunch] > df <- as.data.frame(ds[ds$keep %in% "True", vars], force = TRUE, include.hidden = TRUE)
Error: Client error: (400) Bad Request: The request body must be a valid Crunch Expression. selected function(s) are not allowed.
[crunch] > df <- as.data.frame(ds[ds$keep == "True", vars], force = TRUE, include.hidden = TRUE)
  |=========================================================================================================| 100%

Also a new discovery: it doesn't seem to object if force=FALSE

[crunch] > df <- as.data.frame(ds1[ds1$identity %in% ids, c("sexuality", "identity")], include.hidden = TRUE, force = TRUE)
Error: Client error: (400) Bad Request: The request body must be a valid Crunch Expression. selected function(s) are not allowed.
[crunch] > df <- as.data.frame(ds1[ds1$identity %in% ids, c("sexuality", "identity")], include.hidden = TRUE)

**Comment by jonkeane** [comment]
Thanks for the report. This is a bug in a slightly over-active server-side validation. The fix has actually already been made, and we hope it will be deployed in the next day or so. Sorry for the inconvenience.

Further: the point you make about `force=FALSE` is a good one. In general, you shouldn't _need_ to use `force=TRUE` and you will typically find that the performance of `as.data.frame` on Crunch datasets is better if you don't use `force=TRUE` (the default being `force=FALSE`).
