### ISSUE TITLE
Could not find function name 'setName'

### ISSUE THREAD

**Issue by johnlray** [Crunch-io/rcrunch#299]
I am working my way through the rcrunch documentation and am getting an error in using the `setName()` function, which is described as a quick way to change a folder name in a Crunch dataset. When I use the `setName()` function on an existing directory, however, I get a 'could not find function' error. 

<img width="581" alt="screen shot 2018-07-31 at 2 58 44 pm" src="https://user-images.githubusercontent.com/3180288/43481044-db1c773a-94d2-11e8-8ed2-4c3df0cd4678.png">

<img width="701" alt="screen shot 2018-07-31 at 2 58 48 pm" src="https://user-images.githubusercontent.com/3180288/43481045-db3d1120-94d2-11e8-8737-87bb1337a822.png">

**Comment by jonkeane** [comment]
Thank you for the issue. As you note, the `setName` method isn't quite working properly. We are working on getting that fixed up for you. In the mean time, we recommend renaming folders by moving them with the following syntax which should accomplish what you're looking to do:

```
ds %>% cd("/") %>% mv("Support Section", "The Support Section") 
```

We will update this issue once the `setName` method is resolved.

**Comment by joewilliams-yg** [comment]
So that does not rename the folder - it instead moves the first folder into a subordinate folder

**Comment by joewilliams-yg** [comment]
Although - I am happy to admit that folder names were kind of screwed up to begin with

**Comment by jonkeane** [comment]
Hello all,

We just merged in the fix for this, you should now be able to use both `setName()` and `setNames()` once again. Sorry for the delay and hassle, and thanks again for the report!
