### ISSUE TITLE
Allow `conditionalTransform()` to accept non-Crunch logical expressions

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#309]
I started a branch where I [commented out the check that required the LHS (left-hand-side) to all be CrunchLogicalExprs](https://github.com/Crunch-io/rcrunch/blob/allow-CrunchExpressionLess-conditional-transforms/R/conditional-transform.R#L160-L167) This works for what I needed it to do (though the test that checked this fails and needs updating).

There are a few things to decide on this going forward: A few lines later, we use `datasetReference` to get the dataset object and then pull down the number of rows to check our transform. I've made it so that this dataset reference can now come from at least one LHS or the RHS, but it must be present in one or the other. That sounds like ok behavior*, and if we accept it we will need to change some of the validation to ensure that there is _at least one_ CrunchExpr in either the LHS or RHS.

`*` - a few reasons this seems reasonable to me: in the case that made me run into this it was actually much quicker to pre-compute locally the logicals for determining each rows membership, but I still wanted the value to be placed to be from somewhere else in the dataset. So my formulas looked like: `logicalExpression ~ CrunchExpr`. We definitely also need to support cases where the RHS has an expression (eg an else condition you want to just put "other"). But at least one of the sides of at least on of the conditions should have a `CrunchExpr` in it somewhere, else: why use `conditionalTransform()` since you could just make the variable with the local values.

**Comment by nealrichardson** [comment]
Done in https://github.com/Crunch-io/rcrunch/pull/312
