### ISSUE TITLE
delete and update for multitables

### ISSUE THREAD

**Issue by malecki** [Crunch-io/rcrunch#33]
It would be nice to be able to delete and update multitables rather than just `newMultitable`

**Comment by nealrichardson** [comment]
`delete` should already exist: `Multitable` inherits from `ShojiObject`, which has a `delete` method. "Update" metadata fields like "name" and "is.public" should be trivial to add, borrowing from the Filter object methods. Updating the template/expression is more involved: needs list-like methods for extracting and inserting.
