### ISSUE TITLE
New error when moving a dataset into a project (Invalid graph)

### ISSUE THREAD

**Issue by joewilliams-yg** [Crunch-io/rcrunch#331]
**I have been using the same script for months and now it is broken when moving a dataset into a project.**

Error: Client error: (400) Bad Request: Invalid graph: must contain all index items
 
**The error message isn't particularly clear what is missing in the commands.
I have tried following the instructions in the vignette for moving datasets around.**

[crunch] R> proj <- projects()[["Daily Crunchbox"]]
[crunch] R> proj %>% 
+   mv(ds, "Daily Crunchbox")
Error: Client error: (400) Bad Request: Invalid graph: must contain all index items

[crunch] R> proj <- projects()[["Daily Crunchbox"]]
[crunch] R> proj %>% 
+   mv(ds, "/")
Error: Can't move a dataset to the top-level project

[crunch] R> proj %>% 
+   mv(ds, .)
Error in cd(x, path, create = TRUE) : 
  argument "path" is missing, with no default

**Background:  I have created a new dataset and need to move it into a project.  So I am moving from the top level personal folder into a project.**

**Couple of things I have noticed:
Inspecting the "proj" object - it looks different that the output in the vignette.**
[crunch] R> proj <- projects()[["Daily Crunchbox"]]
[crunch] R> proj
/Daily Crunchbox/ 
  [1] "Crunchbox Huffington Post 20161017 - World View"                                 
  [2] "Crunchbox Huffington Post 20161013 - Sexual Assault"

**Comment by nealrichardson** [comment]
Thanks for the report. I believe you want `projects() %>% mv(ds, "Daily Crunchbox")`, or `projects()[["Daily Crunchbox"]] %>% mv(ds, ".")` should also work (your example had `.` unquoted. `datasets(proj) <- ds` does still work as well.

As for the "graph" error, I believe the latest commit on GitHub should have addressed it (it did for me on Friday after Delia reported similar); if not, then the server deploy that will happen Monday should. 

Thanks also for the note about the print method/vignette discrepancy. We'll address that. As you can see, we're starting to roll out some changes to projects, including the ability to nest projects within projects and grant different permissions to them, and later growing to include features like project-level settings and branding and user analytics. Apologies for any turbulence along the way.

**Comment by joewilliams-yg** [comment]
Yeah....that isn't quite working....

[crunch] R> ds <- loadDataset("Daily Crunchbox (20180928) HuffPost - Kavanaugh confirmation")
[crunch] R> projects() %>% mv(ds, "Daily Crunchbox")
Error: Client error: (400) Bad Request: Invalid graph: must contain all index items

So I tried:

[crunch] R> ds <- loadDataset("Daily Crunchbox (20180928) HuffPost - Kavanaugh confirmation")
[crunch] R> projects()[["Daily Crunchbox"]] %>% mv(ds, ".")
[crunch] R> 

Which initially looked like a success, but that created a folder "." in Daily Crunchbox project

[crunch] R> ds <- loadDataset("Daily Crunchbox (20180928) Trump Tweets")
[crunch] R> proj <- projects()[["Daily Crunchbox"]]
[crunch] R> datasets(proj) <- ds
Error: Client error: (400) Bad Request: Invalid graph: must contain all index items

**Comment by nealrichardson** [comment]
Ok, I believe the commit I just pushed (https://github.com/Crunch-io/rcrunch/commit/d66b9fc10a6bff380d4394b09936b8e45a49961c) should prevent the 400 Bad Request (at least that server validation won't be hit because it won't send a "graph" at all). I'm optimistic that if you install the latest and retry, it will work.

I'll take a look at the "." handling next, that's clearly not right.

**Comment by nealrichardson** [comment]
Closing this issue as I think these problems have been resolved. Please reopen if you're still having trouble with this issue. FYI our backend team is investigating a different authorization error we've been notified about.
