### ISSUE TITLE
Implement Means of Scale

### ISSUE THREAD

**Issue by slobodan-ilic** [Crunch-io/rcrunch#341]
Categorical variables (and perhaps others) allow a *numeric-value* to be
assigned to each category. This could be something like "like=1, dislike=-1,
neutral=0", or possibly "one-child=1, two-children=2, three-or-more=3".

These numeric values impose a quantitative *scale* on an otherwise
non-numeric variable, and thereby allow quantitative operations on that
variable.

Taking the mean value is one of those quantitative operations, and
"scale-mean" refers to calculating the *mean* value of the values on this
numeric *scale*.

**Comment by jonkeane** [comment]
There's already basic support for adding mean and medians for categorical variables that have numeric values (see: https://crunch.io/r/crunch/reference/addSummaryStat.html and https://crunch.io/r/crunch/reference/SummaryStat.html).

There are improvements on the way as well in #335 if you want to see the full range of possibilities I recommend checking out that PR and do let me know if you run into any issues with it.
