### ISSUE TITLE
`as.data.frame()` with `force = TRUE` can't handle variable aliases with spaces

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#347]
This is slightly different from #305 (which I can't quite replicate now).

What's going on is the csv that was written is being read in by https://github.com/Crunch-io/rcrunch/blob/master/R/as-data-frame.R#L92 and spaces in the variable aliases (as well as other characters that dataframes dis-allow are being changed to `.`, then we try and use the non-changed variable aliases to look up the column in the dataframe on lines like https://github.com/Crunch-io/rcrunch/blob/master/R/as-data-frame.R#L131 which return NA, hence not seeing any data.

```
[crunch] > ds$`Party Reg`
Party Reg (categorical)
Party Registration from File

                   Count
Democrat             210
Republican           105
Unaffiliated/Other    35
[crunch] > 
[crunch] > as.data.frame(ds[,"Party Reg"], force = TRUE)
  |============================================================================================================================================| 100%
    Party Reg
1        <NA>
...
350      <NA>
Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```

**Comment by nealrichardson** [comment]
Should the server export the header row with quoted strings?

**Comment by jonkeane** [comment]
That wouldn't hurt, but it also doesn't change the behavior on R's end here.
