### ISSUE TITLE
Find a way to remove filters from deck slides

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#360]
One source of errors is that decks have filters that no longer exist. We should make it easy for someone to remove (or change) all the filters on a series of slides for a deck quickly.

**Comment by nealrichardson** [comment]
`filter(slide) <- NULL`, and `filter(analysis) <- NULL` for even finer control, yeah? idk that there would be much value in `filter(deck) <- NULL` but it would follow naturally.
