### ISSUE TITLE
Finish `changeCategoryID` function

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/rcrunch#38]
https://github.com/Crunch-io/rcrunch/compare/change-cat-id has a working function, a passing test, and a TODO list for what needs to happen to finish it up.

**Comment by jonkeane** [comment]
- [ ] Document
- [ ] Export
- [ ] Add more input validation and tests of
- [ ] Add tests for working with array variables, and extend function if needed

**Comment by nealrichardson** [comment]
Done in #47
