### ISSUE TITLE
Print even really ridiculously long filter expression terms

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/rcrunch#39]
https://github.com/Crunch-io/rcrunch/commit/5ee13d9c56575c34a47a08496c0495ef976886b2 fixed the printing of long expressions, which failed when `deparse` returned a character vector of length >1. But now some have lamented that the truncation is also suboptimal because they can't see all of the values that are included in the filter expression, which is important to know what it does.

**Comment by jonkeane** [comment]
Fixed with #45 along with added flexibility to truncate when we want to.
