### ISSUE TITLE
Documentation wrong for addSlide vizType

### ISSUE THREAD

**Issue by gergness** [Crunch-io/rcrunch#403]
Conversation with Matt "HorizontalGroupedBarPlot" but should be "HorizontalBarPlot" @malecki

**Comment by gergness** [comment]
Assuming complete list is here: https://github.com/Crunch-io/whaam/blob/8a976e52d96bed3f2c0a6c8535f9e6984d49a994/base/crunch-viz/viz-type-picker/viz-type-picker.js#L7-L16

**Comment by malecki** [comment]
fixed by https://github.com/Crunch-io/rcrunch/commit/8fe7fd882da8101e957a4c99b4de262930e181eb
