### ISSUE TITLE
hideByName transform for slides

### ISSUE THREAD

**Issue by malecki** [Crunch-io/rcrunch#406]
something that obscures the details of 

```
crPATCH(analysis(slide[1], I('body: { transform: {rows_dimension: {categories: [{id: 3, hide: true}]}}'))
```

**Comment by malecki** [comment]
They would potentially also like to be able to set an explicit order using R to sort by value etc.
```
{type: "explicit", element_ids: [2, 1, 3]}
```

**Comment by gergness** [comment]
Part of the problem is that `analysis(slide)<-modified_analysis` doesn't actually submit a `crPATCH`. It uses `modifyCatalogInPlace` which I think is a mistake, but needs further digging
