### ISSUE TITLE
Expression for any/all subvariables with a given value

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/rcrunch#41]
(1) It's not uncommon to want to create a filter expression that is true where any of some set of multiple-response values are selected. For a categorical variable, 

    ds$var %in% c("Cat", "Dog")

does that fine because `var` can either be "Cat", "Dog", or something else, but it can't be both "Cat" and "Dog". With multiple response, you need "any" or "all" around that (or maybe "any" is implied, and `all(ds$var %in% c("Cat", "Dog"))` changes the logic).

The API supports any/all functions for multiple response, so we can support them in R. This should not be too challenging.

(2) For categorical arrays, the logic is a little different because the right-hand side of the expression denotes categories and not subvariables. I'm not sure what the API supports currently; you can achieve this with a series of `&`s or `|`s, but that is suboptimal in that the original logic is lost in translation to the query.

(3) Users also would like to be able to specify a subset of subvariables to evaluate the expression for. For arrays, that means for example 'any of these three subvariables have the value "Strongly agree" or "Somewhat agree"'. This may be possible in the API now, either as a series of &s or by defining some derived expression on the fly; neither would be pretty.

**Comment by malecki** [comment]
The database now has this expression: `array_subset` but it might be `subset_array` to do (3).

**Comment by gergness** [comment]
closed via #464
