### ISSUE TITLE
Replace case-statement interactVariables in R package with interaction variable derivation.

### ISSUE THREAD

**Issue by gergness** [Crunch-io/rcrunch#410]
Can't find anything in API Docs about interact variable derivation.
https://docs.crunch.io/search.html?q=interact&check_keywords=yes&area=default

Does this indicate anything about the stability?

---

Searching through zz9 code, found this:
https://github.com/Crunch-io/zoom/blob/21c1563595a28152d3156960f2505ddac48b4a13/zz9/zz9d/src/zz9d/funclib/miscfuncs.py#L589

Looks like zz9 doesn't support the naming conventions provided by the R package.

**Comment by malecki** [comment]
we should probably warn that the 'separator' arg will be ignored henceforth
