### ISSUE TITLE
"interaction" method for Crunch variables

### ISSUE THREAD

**Issue by nealrichardson** [Crunch-io/rcrunch#42]
`base::interaction` takes 2 or more variables and returns a factor that is the cartesian product expansion of their unique values. (Example: "gender" crossed with "age" that has been binned into four groups, resulting in 8 valid categories of intersection and 7 missing categories.)

If this doesn't get officially implemented server-side, https://github.com/Crunch-io/rcrunch/issues/36 will allow it to be done on the R client side.

**Comment by nealrichardson** [comment]
Done in https://github.com/Crunch-io/rcrunch/pull/56

**Comment by persephonet** [comment]
it'd be great if there were a "drop empty" option where you could drop categories that don't have any responses. additionally, i think that new categories should be added as data are appended:

`[crunch] > ds1$show
show (categorical)

                                        Count
The Big Bang Theory                         2
Class of '92: Still Out of Their League     1
test                                        1
[crunch] > ds2$show
show (categorical)

                    Count
test                    1
The Big Bang Theory     1
[crunch] > ds1$channel
channel (categorical)

     Count
BBC1     2
E4       2
[crunch] > ds2$channel
channel (categorical)

     Count
BBC1     1
E4       1
[crunch] > ds1$channel_show_interaction
test (categorical)

                                              Count
BBC1: Class of '92: Still Out of Their League     1
E4: The Big Bang Theory                           1
E4: Class of '92: Still Out of Their League       0
BBC1: The Big Bang Theory                         0
[crunch] > ds1 <- appendDataset(ds1, ds2)
  |===============================================================================================================| 100%
[crunch] > ds1$channel_show_interaction
test (categorical)

                                              Count
E4: The Big Bang Theory                           2
BBC1: Class of '92: Still Out of Their League     1
E4: Class of '92: Still Out of Their League       0
BBC1: The Big Bang Theory                         0`

**Comment by nealrichardson** [comment]
@persephonet "empty" as in the input variable categories don't have any values or that the resulting "intersected" categories don't have any values? If the latter, seems easy enough for you to mark those as missing after creating the variable, or just let the "hide empty" feature in the UI handle it for you.

Unfortunately we can't dynamically update the intersection of categories when new categories are added to the input variables because that's not how the derivation works--it's just making a case variable.
