### ISSUE TITLE
should tabook move to the export endpoint?

### ISSUE THREAD

**Issue by gergness** [Crunch-io/rcrunch#420]
Also testing is light on tabbook

**Comment by malecki** [comment]
(Obviously it needs to, for people to be able to use the new and expanding `options`) —
1. argument (with an `options` default) `use_legacy_tabbook_endpoint`
2. `format` used to be character, but now is an object in `options`; so
If as crunchtabs I want `format="json"` no harm done, but throw a warning about the new arg name.
If I need `format=list(pval_colors=TRUE)`, I need to use `output_format`
