### ISSUE TITLE
Add R support for qualitative color palettes (transforms on slides)

### ISSUE THREAD

**Issue by jsharnowski** [Crunch-io/rcrunch#434]
The spec for whaam support for qualitative color palettes is located at:
https://www.notion.so/crunch/Dashboards-Color-Palettes-PRD-1f41592395d74962853ddc14853267ba

In the context of a whaam color palette spec meeting on 14-April, we did a bit of brainstorming for how support might be added in R.  We reached no definite decisions, but here are some thoughts that were raised during that meeting:
- In general, we need to define how slides are created using R, in consideration of supporting the color palettes.
- Can the API be updated to automatically apply the default color palette?  There would also need to be a way to override the default palette.
- Slide create requests could include the applied default color palette in the payload to create a slide.  If the transform is not present, then the API would look up the default organization color palette and apply it.
- Recommendation is that we do not actually put a transform hack in the create slide API.

Related issue:  https://github.com/Crunch-io/rcrunch/issues/406 - R doesn’t know about a lot of existing slide transformations

**Comment by gergness** [comment]
Some brainstorming:

```
# New slideTransform helper:
slideTransform(
    palette = NULL, # AnalysisPalette or character vector
    hide = NULL, # IDs or string category names
    renames = NULL, # Named vector (int ids or current names, named by desired names)
    order = NULL, # IDs or string category names
    insertions = NULL, # rcrunch:::Insertions object
    ... # (Can pass in `name` or `description`, also allows expandability)
)

# Used in
# transforms<- Slide, <list of slideTransforms> (new)
# newSlide(transforms = <list of slideTransforms>)


# Example set a palette and hide a category
newSlide(
    deck,
    ~age_cat,
    "Age Categories",
    transforms = list(
        rows_dimension = slideTransform(
             palette = analysisPalettes(ds)[[1]],
             hide = "65+"
        )
    )
)

# AnalysisPalette Class (or maybe CrunchPalette) (I don't want to use just `palette`)

# analysisPalettes Generic
# (returns list of palettes associated with it)
# - Dataset 
# - Dataset Folder
# - UserEntity

# Postpone:
# - create/delete palettes on folder/account
# - Showing slideTransforms in cubes retreived from the slide in R
```
