### ISSUE TITLE
newSlide should take a filter argument

### ISSUE THREAD

**Issue by gergness** [Crunch-io/rcrunch#436]

**Comment by gergness** [comment]
learn from work on tabbook filter

**Comment by gergness** [comment]
It should also take a weight argument

**Comment by gergness** [comment]
To revisit when working on this, why do we use `filter()` and `filter<-()` generics on slides instead of using existing generics `filter()` and `filter<-()`

**Comment by malecki** [comment]
todo along with whatever slide analysis transforms we end up implementing

**Comment by gergness** [comment]
fixed in #542
