### ISSUE TITLE
prop.table fails on TabBookResults for arrays and numerics (internal: ‘new tabbook query builder’)

### ISSUE THREAD

**Issue by 1beb** [Crunch-io/rcrunch#437]
When attempting to run `crunch::prop.table` on a categorical array question. I received the following error: 

It cropped up after about 10 days of working. Then, magically disappeared on the same day. There was some discussion about a potential UTF-8 related error . However, if that was the case the error message is poor. I can provide more details and an example dataset where this occured via slack. 

```
Error: Margin 3 exceeds Cube's number of dimensions (2) 
16.
stop(..., call. = call.) 
15.
halt("Margin ", max(margin), " exceeds Cube's number of dimensions (", 
    sum(!selecteds), ")") 
14.
check_margins(margin, selecteds) 
13.
cubeMarginTable(x, margin) 
12.
margin.table(x, margin) 
11.
margin.table(x, margin) 
10.
crunch::prop.table(noTransforms(book[[vi]][[vix]]), margin = c(2, 
    if (is_array_type) 3)) 
9.
crunch::prop.table(noTransforms(book[[vi]][[vix]]), margin = c(2, 
    if (is_array_type) 3)) at tabBooks.R#55
8.
...
```

**Comment by malecki** [comment]
The exact shape of the `MultitableResult` for some row variables (specifically arrays and numerics) changed inadvertently but under the control of a feature flag. The flag has been disabled in production and will make sure to get some crunchtabs tests running against a non-production test host before flipping it again.

**Comment by malecki** [comment]
array query builder stable in production and no longer affecting crunchtabs users the way a bug with it seemed to back in april
