### ISSUE TITLE
tabbooks taskreporter reporting complete before task finished causing 404

### ISSUE THREAD

**Issue by 1beb** [Crunch-io/rcrunch#438]
When attempting to export a `tabbook` from crunch, I'm often getting 404 responses that appear to resolve themselves shortly after. 

```
Error : Client error: (404) Not Found: https://player-crunch-io.s3.amazonaws.com/export/tabbooks/export_tabbook%3A6defced016634340a9cde26878ba0a06%24342379b941e33b23ae0f777e45df0f2e/<DATASET-NAME>.json?Signature=<SIG>%3D&Expires=<EXPIRY>&AWSAccessKeyId=<ACCESSKEYID>
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
```

I recognize that the endpoint was changed recently, could it be related?

**Comment by malecki** [comment]
This may occur by rare coincidence that the tab book was generated at the moment it was deleted when a cache was purged.
The cache is rarely purged, but must be when similar but not identical requests are resolved to the same previously-generated cached result. The last time it was dumped corresponds to the time of this report.

**Comment by 1beb** [comment]
I would like to report that this is happening very frequently. Yesterday, this happened to me about 10 times over the span of about 5 hours. I don't think that is congruent with the rate of purge you mentioned in your last comment. Or is it?

**Comment by 1beb** [comment]
Can confirm having the same issue today.

**Comment by 1beb** [comment]
Reopening based on discussion: 

- temporary fix is setting larger retry wait in branch
- eventually will be fixed after investigating taskreporter

**Comment by malecki** [comment]
Just leave the retry. Somehow this doesn’t even affect our own test infrastructure to be able to prove an api fix.
