### ISSUE TITLE
Add weighting / other batteries included to newExampleDataset

### ISSUE THREAD

**Issue by 1beb** [Crunch-io/rcrunch#443]
```
> library(crunch); login()
> ds = newExampleDataset()
> weightVariables(ds) 
> NULL
```

When writing vignettes or creating examples for using R crunch, it would be useful if the example dataset came with a few more batteries included.

- A weighting variable
- Some variables that would traditionally be used as banners in a cross tabulation (age, gender, age cuts)

We, internally, already have a candidate dataset that is an extension of the current one.

**Comment by 1beb** [comment]
If you could show me how to convert a ds to the json / csv formats you have in https://github.com/Crunch-io/rcrunch/tree/master/inst/example-datasets I would submit a PR for this

**Comment by malecki** [comment]
@1beb check out the new [Schema endpoiint](https://docs.crunch.io/endpoint-reference/endpoint-schema.html) — it provides a view of base data (not derivations) consistent with what is accepted in a create-dataset payload. Reminds me we should think about how to expose and interact with that endpoint here.

**Comment by 1beb** [comment]
Is there an example of how to include a weighting variable?

**Comment by 1beb** [comment]
Ok, this looks about right so far: 

```
toJSON(crGET("https://app.crunch.io/api/datasets/<DATASETID>/schema"))
```

But how do I generate the csv?

**Comment by malecki** [comment]
`write.csv(as.data.frame(`?

**Comment by gergness** [comment]
There's also `exportDataset`

**Comment by 1beb** [comment]
The problem I'm having is that the `weight` variable doesn't appear to come through in the schema. 

reprex: 

```
library(crunch)
ds = newExampledataset() 
ds$weight = makeWeight(ds$q1 ~ c(0.75, 0.15, 0.10), name = "weight")
modifyWeightVariables(ds, "weight") # Assign "weight" as the weighting variable
exportDataset(ds, "example-dataset.csv") # has a column called weight as expected
# write.csv(as.data.frame(ds), "examples-dataset.csv") # has weight
toJSON(crGET("https://app.crunch.io/api/datasets/<DATASETID>/schema")) # no weight var
```

**Comment by 1beb** [comment]
Closing for now. Identified API issue where numeric variables output ids at schema end point making automatic round trips of data creation require a lot of munging.
