### ISSUE TITLE
rowwise n_unique

### ISSUE THREAD

**Issue by malecki** [Crunch-io/rcrunch#456]
The idea here is to pull data (as happens in lm/glm) to compute a rowwise operation. Like `cut`/`interactVariables`, we want to be able to swap out the R-based implementation with a database call when a database function is available.

The result should be a VariableDefinition where *today* the result is Numeric with a vector of the values that we compute locally. When the database function is available, it can be replaced with a VariableDefinition with a derivation expression containing the equivalent db function.

Return a column of the count of unique values across the columns in an array.
https://www.tidyverse.org/blog/2020/04/dplyr-1-0-0-rowwise/
https://dplyr.tidyverse.org/reference/n_distinct.html

In [numpy >1.13](https://numpy.org/doc/stable/reference/generated/numpy.unique.html), this is done with `np.unique(array, axis=0, return_counts=True)`.

**Comment by malecki** [comment]
Missing data handling is TBD and probably differs by default between R and Python. I have a hunch we want `na.rm=TRUE` as an option and possibly the default.

**Comment by gergness** [comment]
I think people will want to handle "all missing" different than a mix of missing and a single value, so I don't think `na.rm` is the right concept.

``` r
library(dplyr)

x <- tibble::tribble(
   ~x1,   ~x2,  ~x3,
 "Yes", "Yes", "Yes", # Clearly a flatline
 "Yes", "Yes",  "No", # Clearly not a flatline
    NA,    NA,   NA, # I think depends on the context
 "Yes", "Yes",   NA  # I think depends on the context
)

x %>% 
  mutate(
    # what `na.rm = TRUE` sounds like to me, useful when skipping a question means no effort
    v1 = apply(x, 1, function(x) length(unique(x[!is.na(x)])) < 2),
    # what `na.rm` = FALSE sounds like to me, missing is treated as a separate category
    v2 = apply(x, 1, function(x) length(unique(x)) < 2),
    # A third option, useful when there are skip patterns so a respondent may not get 
    # asked a whole section of questions, but missing otherwise is a separate category
    v3 = apply(x, 1, function(x) !any(is.na(x)) & length(unique(x)) < 2)
  )
#> # A tibble: 4 x 6
#>   x1    x2    x3    v1    v2    v3   
#>   <chr> <chr> <chr> <lgl> <lgl> <lgl>
#> 1 Yes   Yes   Yes   TRUE  TRUE  TRUE 
#> 2 Yes   Yes   No    FALSE FALSE FALSE
#> 3 <NA>  <NA>  <NA>  TRUE  TRUE  FALSE
#> 4 Yes   Yes   <NA>  TRUE  FALSE FALSE
```

**Comment by gergness** [comment]
straightline not flatline

**Comment by gergness** [comment]
both functions should return logicals
