### ISSUE TITLE
tabBook multiple weights

### ISSUE THREAD

**Issue by 1beb** [Crunch-io/rcrunch#506]
### Problem

There is often a need to present information with more than one weighting scheme. Classic examples are, for example: showing weight by likely voter vs. registered voter, showing different weights for an initial and recontact question, and lastly, different weights for a wave of a tracker.

`tabBoook` provides a useful interface to pull this information from crunch. However, it currently only allows for specification of a single weight. The goal of this issue is to discuss an abstraction on top of tabBook that allows researchers to pull down tabBook summarized data using a variety of weights. 

The most common use case would be one or more (probably no more than 5 to 10) variables being attributed an alternative weight. Importantly, a researcher may often desire the same question weighted in different ways. 

### Proposal

The simplest solution would be to extend the `weight` parameter of the `tabBook` function. The default is NULL or `crunch::weight(dataset)`. If we made it so that it also accepted a named vector of weights or a list of then 

```
tabBook(
   ..., 
   weight = crunch::weight(dataset) # The default, which could be NULL
)

# This solution would be ideal if a small number of variables required different weights

tabBook(
   ..., 
   weight = c('alias1' = 'weight1', 'alias2' = 'weight2')
)

# This solution would be idea if there was larger a one-to-many relationship between weighting and variables

tabBook(
  ..., 
  weight = list(weight_var = c("alias1", "alias2"), weight_var2 = c('alias1', 'alias2'))
) 
``` 

In each case above, the abstraction would loop through the API requests in the same order presentation of the multitable. 

#### Notes

Much of `crunchtabs` existing functionality uses a fake or dummy banner to generate toplines. Multitable input is generated as follows: 

```
  bnr <- banner(
    ds,
    vars = list(
      'Results' = all_aliases[all_types %in% c("categorical", "multiple_response")][1])
  )
```

See mock: https://github.com/Crunch-io/rcrunch/compare/tabook-multi-weights?expand=1

**Comment by gergness** [comment]
Seems reasonable to me!

Some initial thoughts:

1) I think it'd be best do one request per unique weight by combining all the template variables that use that weight into a request, but (my interpretation of) the pseudo code makes it look like you are going to do a request per variable+weight combination in the multitable template.

2) I'm usually all for flexible options in arguments, but having the named vector as well as the list version is confusing to me because the meaning of the names/values are flipped (vector: names are weight aliases & values are template aliases, list is the other way around). I think this is an infrequent enough need that just allowing the list version is okay. If you think we need another way to specify, maybe it could be a two column data.frame as an alternate method?

3) I'm not sure I understand when you'd want `include_original_weighted`. I lean towards removing this and saying that if you want complex weights you have to use a complete specification.

4) Need a way to specify in complex weight specification that some variables go unweighted. Thoughts on how best to do this? Unnamed vectors in the list?

**Comment by 1beb** [comment]
re 1. Agree. The part I need to figure out is how to chain the results objects together appropriately so it doesn't cause downstream problems for crunchtabs.

re 2. I think the list of `list(weight = c(alias, alias), weight2 = c(alias, alias))` is the best approach here. It's more verbose but less programming.

re 3. The reason we are considering this behavior is to allow for a researcher to specify custom weights to be used from the perspective of crunchtabs. Let's break this thought out a bit: 

- The researcher specifies the variables that they want and the weights. Datasets are almost always already weighted with some default scheme. So, how do we identify if the researcher wants to see the variable presented for both the default weighting of the dataset and the custom weight? We need something to tell us the researchers intention. We could enforce an explicit definition but that may not be intuitive. Here's an example of how it works from crunchtabs: 

```
# imagine ds with variables q1,q2,q3, and weights w1, and w2 where the default weight is w1
topline_results <- crosstabs(ds, vars = c('q1', 'q2', 'q3'), weight = list(w2=c('q2')) 
writeLatex(topline_results, ...)
```

The result I would expect here might be: 

- q1 with w1
- q2 with w2
- q3 with w1

But a common use cases, the researcher may be interested in the ability to include q2 with the default weight as well: 

- q1 with w1
- q2 with w1
- q2 with w2
- q3 with w1

We can have them do so explictly: `weight = list(w1 = c('q2'), w2 = c('q2'))`, or we can have them flag it. `include_original_weight`. I think this case is likely to be used frequently. 

When you add 20-30 more political statements for RV/LV, we've just saved the researcher a lot of typing and potential frustration in the future over hard coded weights. 

4. I suspect that this would be best presented as a separate parameter like "unweighted" that accepts a character vector of aliases.

**Comment by 1beb** [comment]
We removed include_original_weighted and made that the default behavior. A user is unlikely to pass a complete dataset and expect to receive only their custom weights in return. They can subset the dataset. Downstream in crunchtabs, this is exactly what we do. We ask the user to present us with their desired variables, then we subset the database by those variables (plus any custom weights they requested) and send those to the tabBook endpoint.  

Design is as follows: 

1. Given a dataset and a list of weight and alias vector pairs
2. Create a data.frame that is in dataset order, that includes columns: alias, weight, order, and position. Where position is a simple incrementing number by weight. a1 w1 p = 1, a1 w2 p = 1, a2 w1 p 2, and so on where: a is alias, wX is weight, and p is position. 
3. Loop over the data.frame by weight, and retrieve the tabBook from the API
4. Repackage the result by looping through the initial tabBook result using the row number and the position.

**Comment by 1beb** [comment]
Closing here because this is already integrated into crunchtabs.
