### ISSUE TITLE
Test formula methods more fully

### ISSUE THREAD

**Issue by jonkeane** [Crunch-io/rcrunch#53]
There's currently quite a bit of coverage for formula methods because they are called extensively in other tests, but there probably ought to be true unit tests for some aspects and properties of some of the formula methods.

**Comment by nealrichardson** [comment]
https://github.com/Crunch-io/rcrunch/compare/deep-arrays-131284751#diff-bca16a658230316c54d104f659939c04 adds some `formulaToCubeQuery` tests.
