### ISSUE TITLE
searchDatasets should convert lists to JSON

### ISSUE THREAD

**Issue by mainwaringb** [Crunch-io/rcrunch#546]
As of the current CRAN version (1.27.27), `searchDatasets` appears to require literal JSONs (passed as characters strings). It should be able to call `toJSON` and convert an R-formatted list to a JSON.

For example, this call currently works: 

```
searchDatasets(
    "privacy", 
    f='
    {
      "dataset_ids" : 
      [
        "633bb87f76fc48528d5ef78b47c7c4e0", 
        "ba39c4b8af4645fc8cda197709028209"
      ]
    }'
)
```

However, the call with an equivalent R list returns `Client error: (400) Bad Request: f parameter should be valid JSON`:

```
searchDatasets(
  "privacy", 
  f = list
  (
    dataset_ids = c
    (
      "633bb87f76fc48528d5ef78b47c7c4e0", 
      "ba39c4b8af4645fc8cda197709028209"
    )
  )
)
```
Constructing literal JSONs is error-prone if done by hand (no linting), a cumbersome extra step if done formulaically, and a likely confusion point for some users. As discussed with @malecki

**Comment by gergness** [comment]
Sorry, lost track of this, thanks for the suggestion!

For future reference, crunch does export a `toJSON` function so if you want help making JSON for some part of the API that isn't well exposed you could do eg:

```
searchDatasets(
  "privacy", 
  f = toJSON(list(
    dataset_ids = c(
      "633bb87f76fc48528d5ef78b47c7c4e0", 
      "ba39c4b8af4645fc8cda197709028209"
    )
  ))
)
