### ISSUE TITLE
Unable to locate dataset with R even though GUI shows dataset in folder - unless restart R

### ISSUE THREAD

**Issue by joewilliams-yg** [Crunch-io/rcrunch#592]
I have a streaming dataset that should be in the folder "Academic Projects Streaming".  I ran loadDataset() but R returned an error that the dataset was not in the folder.  I looked on Gryphon and discovered the streaming dataset was no longer assigned to any dataset.  On the Gryphon page, I reassigned the streaming survey to the "Academics Projects Streaming" folder.  In the Crunch GUI, I confirmed the streaming dataset is in the folder.  When I re-ran the loadDataset() command, I still received the "not found" error.  I was under the impression that the loadDataset() command would make an API call and find the new dataset, but that is not the case.  There doesn't seem to be a way to refresh what my R session can see.  So I restarted my R session, and only then is rcrunch able to find the dataset.

I have attached screen shots and a text file with information from the console for my session.

[rcrunch_cant_find_dataset.txt](https://github.com/Crunch-io/rcrunch/files/8342188/rcrunch_cant_find_dataset.txt)
![Screen Shot 2022-03-24 at 9 52 14 AM](https://user-images.githubusercontent.com/29802799/159935623-d260bbea-759d-47ef-bf7b-ec6a94c22fa2.png)
![Screen Shot 2022-03-24 at 10 09 27 AM](https://user-images.githubusercontent.com/29802799/159935775-baddc796-0d00-4aa9-9ac5-f947b6aeff77.png)
![Screen Shot 2022-03-24 at 10 09 39 AM](https://user-images.githubusercontent.com/29802799/159935784-5488dc08-05bc-41d7-ae5f-91867906f3a7.png)
![Screen Shot 2022-03-24 at 10 10 13 AM](https://user-images.githubusercontent.com/29802799/159935790-9174e942-f7bd-4665-95ca-bd7feb0f586d.png)
![Screen Shot 2022-03-24 at 10 09 14 AM](https://user-images.githubusercontent.com/29802799/159935643-078d288c-4b2c-4eb9-9411-663838b7d8ee.png)

**Comment by gergness** [comment]
I had forgotten that there's already a `refresh` argument to both `listDatasets()` and `loadDataset()` that gets what you want. 

eg running this should clear the cache before loading, so it won't matter if Gryphon just put the dataset since the last time you listed it.
```
listdatasets(refresh = TRUE)
```
