### ISSUE TITLE
case statements for survey data

### ISSUE THREAD

**Issue by rdrivers** [Crunch-io/rcrunch#64]
A common pattern in survey data is that users are first presented with a multiple response question, e.g. Which of these Web browsers have you used? Then users are asked follow-up question(s) about two or more of the items selected in the first question, e.g. "How often do you use [browser]? The contents of these follow-up questions are not useful, since different people are being asked about different things.

The data will usually have the following structure:

* The initial screening question (determining which brands the respondent will be asked follow-up questions about) will generate variables X1, X2, X3 (etc.) identifying the subject of each of the follow-up questions. These are categorical variables, which have the same brands as categories (e.g., IE, Chrome, Firefox, Safari). Here X1 would identify which browser the first follow-up question is about, X2 the browser that the second follow-up question is about, etc.

* The first follow-up question will generate three variables, Y1, Y2, Y3 (in this case, the usage of browser X1, browser X2, or browser X3, respectively).  The problem is that for some respondents, Y1 could be about X1 for some respondents and X2 for other respondents or vice versa. Y1 contains a mismash of responses that aren't easily analyzable in this format. (There can, of course be multiple follow-ups (e.g., "How satisfied are you with the speed of [browser]?" but I'll stick to just one set of follow-ups for this example.)

What we want is a set of variables giving usage of each of the browsers, e.g. Usage_Chrome, Usage_IE, Usage_Firefox, Usage_Safari. These will be missing if the user wasn't asked about that browser in the follow-up. In R, this could be done using something like

Usage_Chrome <- ifelse(X1 == "Chrome", Y1, ifelse(X2 == "Chrome", Y2, ifelse(X3 == "Chrome", Y3, NA)))

In Rcrunch, we'd like to create derived variables using a case_when function:

ds$Usage_Chrome <- case_when(cases = c(~ X1 == "Chrome", ~ X2 == "Chrome", ~ X3 == "Chrome"),
   values = c(~ Y1, ~ Y2, ~ Y3), default = NA, type = "categorical", categories = c("Chrome", "IE", "Firefox", "Safari"), data = ds)

The cases argument specifies a vector of logical conditions (specified as formulas), which are evaluated sequentially, with evaluation short-circuiting when a TRUE logical condition is found for a case. If no condition is satisfied for a case, the default value is assigned (which should be NA or "no data" if the default argument is omitted). The values argument must have the same number of elements as cases and are also specified as formulas. The formulas in values must be of the type specified by the type argument or something that can be cast to that type. If the type is "categorical", then a list of categories is specified for the output variable. [This is probably insufficient, but hopefully you get the idea].

**Comment by rdrivers** [comment]
Thinking about this, we probably shouldn't borrow the case_when name from dplyr without following its syntax. I'd propose to rename the function to something like conditional_transformation() but otherwise keep the same.

**Comment by nealrichardson** [comment]
This was implemented in https://github.com/Crunch-io/rcrunch/pull/65. Please check it out and let us know how it can be improved. Currently, the function creates a non-derived variable because the server does not support such a derivation function yet; the goal was to work out the logic and requirements in R and then build it on the server once we understood the problem better. We've already learned a lot, and once we've collected your and others' feedback on it, we can look into moving the implementation server-side.
