### ISSUE TITLE
dichotomize deriveArray

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#66]
deriveArray accepts "selections" as an argument but does not actually mark them as selected. Therefore, it can only make categorical_arrays and the user has to dichotomize after the fact.

**Comment by nealrichardson** [comment]
Looks like it's just loose validation that it accepts "selections" and does nothing silently, and ambiguous documentation that doesn't say that "selections" would be ignored in `deriveArray`. 

@jonkeane is looking into implementing this, though. Should be feasible.

**Comment by jonkeane** [comment]
We have updated crunch and rcrunch to accept this. Now you can derive multiple responses directly using `deriveArray(..., selections = [category name(s) to select])`. Let us know if you run into any issues.
