### ISSUE TITLE
ordering(ds) print aliases

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#74]
When `ordering(ds)` is simply printed to the screen, it prints the VariableOrder using the names of the variables. It would be much more useful if it printed the aliases instead given that anyone working with R is using the aliases anyway.

**Comment by nealrichardson** [comment]
The option to print aliases was added in [version 1.14.0](https://github.com/Crunch-io/rcrunch/blob/master/NEWS.md#crunch-1140) (Nov. 2016) but the default was not changed so as not to disrupt. If there's consensus among the package users that the default should change, we can do that.
