### ISSUE TITLE
extendDataset() respect exclusion

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#76]
Right now, `extendDataset` does not respect your exclusion on the right dataset. Therefore, if you do something like 

` exclusion(ds2) <- ds2$dispostion == 'Incomplete'
ds1 <- extendDataset(ds1, ds2, by='identity')`

even those with disposition == "Incomplete" would be extended on.

**Comment by nealrichardson** [comment]
Opened a server-side bug ticket for this.
