### ISSUE TITLE
rollup week start day

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#78]
When using `rollup(ds$var, 'W')` the start of the week is always on Thursday (I'm guessing because 1970-01-01 was a Thursday). Therefore, I have to `as.vector` and `floor_date()` (from the lubridate package) if I want a week variable because clients rarely like Thursdays as the start day. An argument allowing me to specify which day I would like to be the start of the week would save a lot of time.

**Comment by gergness** [comment]
Working on categorical date variables, will supersede this
