### ISSUE TITLE
Combine categories in place (update instead of derive)

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#79]
Occasionally, it is much more useful to combine without deriving because you know that a category or subvariable is permanently going away. For example if there are categories "Don't know" and "Don’t know" [note the fancy quote], a non-derived combine would be much more useful that a derived one. Right now, the code looks something like:

```
ds$var[ds$var %in% "Don't know"] <- "Don’t know"
categories(ds$var) <- categories(ds$var)[!(names(categories(ds$var)) %in% "Don't know")]
```

**Comment by nealrichardson** [comment]
Start with a new function like:

```
collapseCategories <- function (variable, to, from) {
    # Move the values
    variable[variable %in% from] <- to
    # Prune the categories
    categories(variable) <- categories(variable)[!(names(categories(variable)) %in% from)]
    return(variable)
}
```

Adding the necessary validations and accepting whatever kinds of inputs you think appropriate.

We could then try to switch off behavior in https://github.com/Crunch-io/rcrunch/blob/master/R/combine-categories.R (similar to how `copyVariable` has a `deep` argument), though I'm not sure it's a good idea, and even if it is, that it's worth doing. If we did that, we might want to rethink how the combinations are expressed in the function arguments, perhaps having a more concise version using `~` like we have in `makeCaseVariable`. Sounds like a can of worms.

**Comment by GShotwell** [comment]
I like the formula interface for this one, maybe we could do something like: 

```
collapseCategories( ds$var, 
    "don't know  " ~ "don't know, 
    "Don't know"   ~ "don't know")
```
That way we could also allow logical expressions for categories:
```
collapseCategories( ds$var, 
    ds$var  %in% c("don't know  ", "Don't know") ~ "don't know"

collapseCategories( ds$var, 
    str_detect(ds$var, "don't") ~ "don't know"
```

Which could really help with some common data cleaning problems. 

I agree that if we went that route we would need to rethink how combine works. One option would be to add a copy argument to `collapseCategories` which would first take a deep copy of the variable and then do the recoding.

**Comment by nealrichardson** [comment]
I'm not sure what the formula interface buys us here. Your first example is more concise without them:

```
ds$var <- collapseCategories(ds$var, to="don't know", from=c("Don’t know", "don’t know"))
```

And I can do more involved logic without them too:

```
ds$var <- collapseCategories(ds$var, to="don't know", 
    from=grep("don’t know", names(categories(ds$var)), value=TRUE, ignore.case=TRUE))
```

On the last point, `combine` makes a derived variable, so we wouldn't want to substitute something that makes a deep copy--that's not the goal.

**Comment by nealrichardson** [comment]
To be clear, my point about formulas was more about altering/extending `combine` to use them, possibly, since some of the other variable builders do, but I'm not sure it's worthwhile for `collapse`, which does less.

**Comment by GShotwell** [comment]
I guess the main thing it gets you is that you can do multiple recodings in one call like:
```
collapseCategories(
    "Don't know" ~ "don't know",
    "Don't care" ~ "don't care" )
```

**Comment by nealrichardson** [comment]
That's true, although from a performance standpoint there's not much to be gained because the expensive update (`variable[variable %in% from] <- to`) has to be done separately for each formula. 

I also fear that in this case, the formula notation might be confusing and error-prone: which side of the formula is the good one and which side is the one you want to collapse into it? Unlike other functions where one side is an expression and the other side is a value, since they're both strings, we can't easily validate and tell the user that they have it backwards--we won't know the difference. 

In principle I don't have a problem with supporting both ways, but I'm just not sure that it's worth the effort (cost to write, cost to document, cost to maintain) for this function.

**Comment by jonkeane** [comment]
In support of this fear: "I also fear that in this case, the formula notation might be confusing and error-prone: which side of the formula is the good one and which side is the one you want to collapse into it?" In a somewhat parallel function: I can never remember which side is which in `dplyr::rename` every time I have to look at the docs (or try it and wait for it to error if I've got it wrong, which is less costly there).

**Comment by nealrichardson** [comment]
It at least would be salvageable if the user got the formula notation backwards in `collapse`: if you collapsed "Don't know" into "don't know" but wanted it the other way, just rename the category from "don't know" to "Don't know". But it's not ideal.

**Comment by GShotwell** [comment]
That's a good point, and `collapseCategories` is a bit more destructive than `case_when` or `rename` in that it modifies the state of the server, so it makes sense to be simple and explicit.
