### ISSUE TITLE
Derive weights in R

### ISSUE THREAD

**Issue by persephonet** [Crunch-io/rcrunch#80]
An R function for the weighting that is done in the UI would be a huge time saver. Given that the UI one updates for streaming datasets, I would like to be able to set up weighting scripts for all of my streaming datasets to be weighted.

**Comment by nealrichardson** [comment]
http://r-survey.r-forge.r-project.org/survey/html/rake.html is generally what the server is doing, but at first glance, that's not the most intuitive interface IMO. Don't feel constrained by that. As for our API, http://docs.crunch.io/#weights is unfortunately thin, so we should flesh that out as part of this work. I'll help you RTFS to find a test or something that describes the correct payload shape.
